name: Train EfficientNet Fruits Model

on:
  workflow_dispatch:  

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training
        run: |
          echo "🚀 Starting training..."
          python train.py | tee train_log.txt
          echo "✅ Training finished!"

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/efficientnet_fruits.pth

      - name: Upload training logs
        uses: actions/upload-artifact@v4
        with:
          name: training-log
          path: train_log.txt
